# Generated by Django 5.2.12 on 2026-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SponsoredCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
