# Generated by Django 5.2.12 on 2026-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=20, unique=True)),
                ("customer_number", models.CharField(max_length=20)),
            ],
        ),
    ]
