# Generated by Django 5.2.12 on 2026-04-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=50, unique=True)),
                ("customer_number", models.CharField(max_length=50)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_code", models.CharField(max_length=50)),
                ("mailroom_date", models.DateField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patents.patentapplication",
                    ),
                ),
            ],
            options={
                "unique_together": {("application", "document_code", "mailroom_date")},
            },
        ),
        migrations.DeleteModel(
            name="Application",
        ),
    ]
