# Generated by Django 5.1.6 on 2026-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patents", "0002_patentapplication_patentdocument_delete_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="patentapplication",
            name="priority",
            field=models.BooleanField(default=False),
        ),
    ]
