# Generated by Django 5.2.12 on 2026-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patents", "0003_patentapplication_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="patentapplication",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patentapplication",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
